name: Deploy Bagisto to Virtualmin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, mysqli
          coverage: none

      # 3️⃣ Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      # 4️⃣ Install Node dependencies and build assets
      - name: Install Node and Build Assets
        run: |
          npm install
          npm run prod

      # 5️⃣ Create Deployment Package
      - name: Create Deployment Package
        run: |
          zip -r deploy-package.zip . -x ".git/*" ".github/*" "tests/*" "node_modules/*" "vendor/*"

      # 6️⃣ Copy files to server
      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "deploy-package.zip"
          target: "${{ secrets.DEPLOY_PATH }}"

      # 7️⃣ SSH into server and deploy
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}

            # Unzip package
            unzip -o deploy-package.zip -d .
            rm deploy-package.zip

            # Permissions for all files
            chmod -R 755 .
            chmod -R 775 storage bootstrap/cache
            chown -R www-data:www-data .

            # Laravel / Bagisto setup
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            php artisan key:generate
            php artisan config:cache
            php artisan route:cache
            php artisan migrate --force
            # php artisan db:seed  # Only run if needed
            php artisan storage:link

            # Build assets on server (optional if already built in GitHub Actions)
            npm install
            npm run prod

            # Final permissions
            chmod -R 775 storage bootstrap/cache
            chown -R www-data:www-data storage bootstrap/cache
