name: Deploy Laravel to Virtualmin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'   # match your server PHP
          extensions: mbstring, bcmath, xml, curl, mysql
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Create Deployment Package
        run: |
          zip -r deploy-package.zip . -x ".git/*" ".github/*" "tests/*"

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "deploy-package.zip"
          target: "${{ secrets.DEPLOY_PATH }}"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            unzip -o deploy-package.zip -d .
            rm deploy-package.zip

            # Laravel setup
            cp .env.example .env || true
            php artisan config:cache
            php artisan route:cache
            php artisan migrate --force
            php artisan storage:link
            chown -R www-data:www-data ${{ secrets.DEPLOY_PATH }}
            chmod -R 755 ${{ secrets.DEPLOY_PATH }}
